### ISSUE TITLE
SLF4J error

### ISSUE THREAD

**Issue by Triara** [whostolebenfrog/rest-cljer#28]
I'm trying to get it working with speclj, that's my test:

```clojure
(ns microservice-template-clj.mockedRoute
	(:require [speclj.core :refer :all]
			  [ring.mock.request :refer :all]
			  [rest-cljer.core :refer [rest-driven]]
			  [microservice-template-clj.server :as server]))

(describe "Mocked route of the server"
	(it "Must return a 200 OK even though the route doesn't exist"
		(rest-driven
			[{:method :GET :url "/events"} {:type :JSON :status 200}]

			(let [response (server/app (request :get "/events"))]
				(should= 200 (:status response))))))
```

Didn't found any other example with speclj, that's the output

```
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.clojure.core, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.config, being replaced by: #'midje.clojure.core/record?
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.emission.levels, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.util.pile, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.emission.api, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.emission.plugins.util, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.emission.plugins.default-failure-lines, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.util.core, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.1-to-explicit-form.metadata, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.util.recognizing, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.sweet, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.semi-sweet, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.data.prerequisite-state, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checking.core, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.2-to-lexical-maps.fakes, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.util.fnref, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.util.error-handling, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.lexical-maps, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.3-from-lexical-maps.from-fake-maps, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checkers, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checking.checkers.chatty, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checking.checkers.util, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checking.checkers.simple, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checking.checkers.collection, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checking.checkers.collection-util, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checking.checkers.collection-comparison, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.checking.predictions, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.util.laziness, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.1-to-explicit-form.background, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.util.wrapping, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.2-to-lexical-maps.data-fakes, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.2-to-lexical-maps.expects, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.doc, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.0-to-fact-form.tabular, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.1-to-explicit-form.facts, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.data.compendium, being replaced by: #'midje.clojure.core/record?
WARNING: record? already refers to: #'clojure.core/record? in namespace: midje.parsing.0-to-fact-form.formulas, being replaced by: #'midje.clojure.core/record?
.F.

Failures:

  1) Mocked route of the server Must return a 200 OK even though the route doesn't exist
     null
     java.lang.NumberFormatException: null
     	... 2 stack levels elided ...
     	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
     	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     	... 2 stack levels elided ...
     	at microservice_template_clj.mockedRoute$eval9802$fn__9803$fn__9808.invoke(/Users/kristina/proyectos/cloudFrame/bankraft-clj/spec/microservice_template_clj/mockedRoute.clj:9)
     	... 33 stack levels elided ...
     	at user$eval884.invoke(form-init2128607190517350685.clj:1)
     	... 14 stack levels elided ...
```

The other part of my code is a heartbeat route, but this should be relevant.

**Comment by whostolebenfrog** [comment]
Hi, thanks for reporting this. 

I'm not completely sure what's going on from the stacktrace, some kind of bad interaction between midje and speclj I would guess. rest-cljer currently uses a midje fact to determine whether or not the underlying expectations are met - this might be upsetting speclj. Thinking about it I think it would be OK for that fact to be replaced with a clojure.core test - that might fix things but I'll need to give it a try.

It would be nice if this was generic and not tied to midje.

-Ben

**Comment by kelveden** [comment]
@whostolebenfrog I had a very similar problem today when I temporarily downgraded the midje dep in a project from 1.6.3 to 1.5.1.

**Comment by whostolebenfrog** [comment]
Hi @Triara,

I've done some testing and rest-cljer works fine with speclj. I've added some speclj tests in my latest commit to confirm this.

Looking at your code though I can see your problem. rest-cljer mocks out real http calls, that is we spin up an instance of jetty to respond to the http call. You are making an http request using ring.mock - this generates a request map in the form of one that can be applied to a ring / compojure route handler. It doesn't actually make an http call.

If you want to see a full example of using rest-cljer take a look at acceptance.clj in:

https://github.com/mixradio/mr-clojure-exploded

You should be able to alter this from midje to speclj with no problems.

There are also examples of testing with mocked requests into handlers in a very similar manner to ring.mock in:

https://github.com/mixradio/mr-clojure-exploded/blob/master/test/exploded/unit/web.clj

If you are interested you can create your own project from our example using `lein new mr-clojure <your-project-name>`

See: https://github.com/mixradio/mr-clojure for more info.
